FROM centos:6

# build packages
RUN \
  yum install -y \
    gcc gcc-c++ glibc ncurses-devel make rpm-build wget tar git \
  && yum clean all \
  && install -d /root/rpmbuild/SPECS /root/rpmbuild/SOURCES

# checkinstall
RUN \
  yum install -y gettext \
  && rpm -ivh https://raw.githubusercontent.com/tukiyo/mysql4.0.30.el6/master/rpmbuild/RPMS/x86_64/checkinstall-20150420-1.x86_64.rpm \
  && ln -s /usr/local/lib/installwatch.so /usr/local/lib64/installwatch.so

WORKDIR /root/rpmbuild/SOURCES

# get php.src.rpm
RUN wget -q "http://vault.centos.org/6.8/os/Source/SPackages/php-5.3.3-47.el6.src.rpm"
RUN yum install -y yum-utils \
  && yum-builddep -y php-5.3.3-47.el6.src.rpm

# get php source
RUN wget -q "http://jp2.php.net/distributions/php-5.3.29.tar.gz"
RUN tar xzf php-5.3.29.tar.gz
WORKDIR /root/rpmbuild/SOURCES/php-5.3.29
## configure need mysql4.0
RUN yum install -y "https://raw.githubusercontent.com/tukiyo/mysql4.0.30.el6/master/rpmbuild/RPMS/x86_64/opt-mysql4-4.0.30-1.x86_64.rpm"
RUN yum install -y lemon bison
## epel have libmcrypt-devel rec2c packages.
RUN rpm -ivh "http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm"
RUN yum install -y libmcrypt-devel rec2c
## configure
ENV CONFIGURE="--prefix=/usr/local/php --with-apxs2=/usr/sbin/apxs --with-config-file-path=/etc/php --with-pear=/usr/local/pear --disable-cgi --enable-zend-multibyte --enable-mbstring --with-mysql=shared,/opt/mysql --with-openssl --with-mhash=shared,/usr --with-mcrypt=shared,/usr --enable-sockets --enable-pcntl --enable-sigchild --with-gd=shared --with-jpeg-dir=/usr --with-png-dir=/usr --with-zlib-dir=/usr --with-freetype-dir=/usr --enable-gd-native-ttf --enable-gd-jis-conv"
RUN ./configure ${CONFIGURE}
RUN make -s
RUN make install
RUN checkinstall -y -R --pkgname=opt-php-5.3.29 \
  && ls -lh /root/rpmbuild/RPMS/x86_64/*.rpm

RUN /usr/local/php/bin/pear install DB-1.8.2
